export const WeeklyData = [
  {
    spillOver: Math.floor(Math.random() * 100) + 1,
    available: Math.floor(Math.random() * 100) + 1,
    occupied: Math.floor(Math.random() * 100) + 1,
    hollow: 100,
    uuid: 1,
  },
  {
    spillOver: Math.floor(Math.random() * 100) + 1,
    available: Math.floor(Math.random() * 100) + 1,
    occupied: Math.floor(Math.random() * 100) + 1,
    hollow: 100,
    uuid: 2,
  },
  {
    spillOver: Math.floor(Math.random() * 100) + 1,
    available: Math.floor(Math.random() * 100) + 1,
    occupied: Math.floor(Math.random() * 100) + 1,
    hollow: 100,
    uuid: 3,
  },
  {
    spillOver: Math.floor(Math.random() * 100) + 1,
    available: Math.floor(Math.random() * 100) + 1,
    occupied: Math.floor(Math.random() * 100) + 1,
    hollow: 100,
    uuid: 4,
  },
  {
    spillOver: Math.floor(Math.random() * 100) + 1,
    available: Math.floor(Math.random() * 100) + 1,
    occupied: Math.floor(Math.random() * 100) + 1,
    hollow: 100,
    uuid: 5,
  },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 6,
  // },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 7,
  // },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 8,
  // },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 9,
  // },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 10,
  // },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 11,
  // },
  // {
  //   spillOver: Math.floor(Math.random() * 100) + 1,
  //   available: Math.floor(Math.random() * 100) + 1,
  //   occupied: Math.floor(Math.random() * 100) + 1,
  //   hollow: 100,
  //   uuid: 12,
  // },
];
